version: '3'
services: 
  zookeeper:
    container_name: local-zookeeper
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  kafka:
    container_name: local-kafka
    image: wurstmeister/kafka:2.12-2.3.0
    depends_on: 
      - zookeeper
    ports:
      - "9092:9092"
    environment: 
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "test_topic:1:1" #Topic name, partition cnt, replica cnt
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  producer:
    depends_on: 
      - kafka
    container_name: local-producer
    build: 
      context: .
      dockerfile: dockerfile
    stdin_open: true
    tty: true
#  consumer:
#   container_name: local-consumer
#    build: 
#      context: .
#      dockerfile: dockerfile
