version: '3'
services: 
  zookeeper:
    container_name: local-zookeeper
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  kafka:
    container_name: local-kafka
    image: wurstmeister/kafka:2.12-2.3.0
    depends_on: 
      - zookeeper
    ports:
      - "9094:9094"
    environment: 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://192.168.33.52:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "test_topic:1:1" #Topic name, partition cnt, replica cnt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  producer:
    depends_on: 
      - kafka
    container_name: local-producer
    build: 
      context: .
      dockerfile: dockerfile
    stdin_open: true
    tty: true
  consumer:
    depends_on: 
      - kafka
    container_name: local-consumer
    build: 
      context: .
      dockerfile: dockerfile
    stdin_open: true
    tty: true
