# See: https://github.com/cloudhut/kowl/tree/master/docs/config for reference config files.
kafka:
  brokers:
    - kafka-1:29091
    - kafka-2:29092
    - kafka-3:29093

# server:
  # listenPort: 8080