#
# https://better-coding.com/building-apache-kafka-cluster-using-docker-compose-and-virtualbox/
# https://gist.github.com/everpeace/7a317860cab6c7fb39d5b0c13ec2543e
# https://github.com/zoidbergwill/docker-compose-kafka/blob/master/docker-compose.yml
#
version: '3.3'

services:
  emq:
    image: emqx/emqx:latest
    ports:
      - "1883:1883"
      - "18083:18083"

  kafka:
    image: wurstmeister/kafka
    healthcheck:
      test: ps augwwx | egrep [S]upportedKafka
    depends_on:
      - zk
    volumes:
      - "./kafka1/mqtt.properties:/opt/kafka/config/mqtt.properties"
      - "./kafka-connect/kafka-connect-mqtt-1.0-SNAPSHOT.jar:/opt/kafka/libs/kafka-connect-mqtt-1.0-SNAPSHOT.jar"
      - "./kafka-connect/kafka-connect-mqtt-1.2.1.jar:/opt/kafka/libs/kafka-connect-mqtt-1.2.1.jar"
      - "./kafka-connect/org.eclipse.paho.client.mqttv3-1.0.2.jar:/opt/kafka/libs/org.eclipse.paho.client.mqttv3-1.0.2.jar"
    ports:
      - "9092"
    environment:
      #KAFKA_LOG_DIRS: /kafka
      #KAFKA_CREATE_TOPICS: test-topic-1:1:2,test-topic-2:1:2,test-topic-3:1:2
      KAFKA_ADVERTISED_HOST_NAME: 178.128.85.176
      #KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_HOURS: "168"
      KAFKA_LOG_RETENTION_BYTES: "100000000"
      KAFKA_ZOOKEEPER_CONNECT:  zk:2181

  zk:
    image: elevy/zookeeper:latest
    ports:
      - "2181:2181"
      - "2888"
      - "3888"
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 10s
      timeout: 10s
      retries: 3

  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    depends_on:
      - kafka
      - zk
    links:
      - zk
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zk:2181
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true

#  kafka-connect:
#    build: ./kafka-connect
##    image: 1ambda/kafka-connect
#    depends_on:
#      - kafka1
#      - kafka2
#      - kafka3
#    links:
#      - emq
#      - kafka1
#      - kafka2
#      - kafka3
##    volumes:
##      - "./kafka-connect/mqtt.properties:/opt/kafka_2.11-0.10.0.0/config/mqtt.properties"
#    ports:
#      - "8083:8083"
#    environment:
#      CONNECT_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9092,kafka3:9092
#      CONNECT_GROUP_ID: connect-cluster-A
#    healthcheck:
#      test: echo stat | nc localhost 8083
#      interval: 10s
#      timeout: 10s
#      retries: 3
