# https://itzone.tistory.com/722
# https://hub.docker.com/r/wurstmeister/kafka/
# https://better-coding.com/building-apache-kafka-cluster-using-docker-compose-and-virtualbox/
# https://gist.github.com/everpeace/7a317860cab6c7fb39d5b0c13ec2543e
# https://github.com/zoidbergwill/docker-compose-kafka/blob/master/docker-compose.yml
# https://www.kaaproject.org/kafka-docker/
#
version: '3'
services:
  kafka1:
    image: wurstmeister/kafka
    healthcheck:
      test: ps augwwx | egrep [S]upportedKafka
    depends_on:
      - zk1
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: hello-mqtt:1:2,hello-mqtt-kafka:1:2,test-topic:1:2
      KAFKA_ZOOKEEPER_CONNECT:  zk1:2181
      #KAFKA_ADVERTISED_HOST_NAME: 192.168.33.52
      KAFKA_ADVERTISED_PORT: 9091
      KAFKA_LOG_RETENTION_HOURS: "168"
      KAFKA_LOG_RETENTION_BYTES: "100000000"

      
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9091,OUTSIDE://192.168.33.52:9094
      KAFKA_LISTENERS: INSIDE://:9091,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

  zk1:
    image: elevy/zookeeper:latest
    environment:
      MYID: 1
      SERVERS: zk1
    ports:
      - "2181:2181"
      - "2888"
      - "3888"
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 10s
      timeout: 10s
      retries: 3

  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    depends_on:
      - kafka1
      - zk1
    links:
      - zk1
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zk1:2181
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true