version: '3'
services: 
  rabbit:
    container_name: rabbitmq-mqtt-mode
    build: 
      context: .
      dockerfile: dockerfile
    stdin_open: true
    tty: true
    ports:
        - 5672:5672
        - 15672:15672
        - 1883:1883
